tunnel: quick-tunnel
credentials-file: ~/.cloudflared/credentials.json

ingress:
  - hostname: choice-app.trycloudflare.com
    service: http://localhost:5173
  - service: http_status:404

# Désactiver les fonctionnalités problématiques
protocol: http2
no-tls-verify: true
no-autoupdate: true
no-metrics: true
no-chunked-encoding: true
edge-ip-version: auto
retries: 5
grace-period: 30s
